name: Terraform Huawei Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del Código
        uses: actions/checkout@v3

      - name: Configurar Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.6

      - name: Inicializar Terraform
        run: |
          terraform init

      - name: Validar Configuración
        run: |
          terraform validate

      - name: Aplicar Infraestructura
        env:
          HCLOUD_ACCESS_KEY: ${{ secrets.HCLOUD_ACCESS_KEY }}
          HCLOUD_SECRET_KEY: ${{ secrets.HCLOUD_SECRET_KEY }}
        run: |
          terraform apply -auto-approve
